### ISSUE TITLE
puppetlabs_spec_helper/tasks/beaker no longer exists

### ISSUE THREAD

**Issue by op-ct** [simp/rubygem-simp-beaker-helpers#165]
puppetlabs_spec_helper [removed `puppetlabs_spec_helper/tasks/beaker` and bumped to 4.0.](https://github.com/puppetlabs/puppetlabs_spec_helper/pull/338)

This doesn't affect the tests for rubygem-simp-beaker-helpers, because its `Gemfile` pins `puppetlabs_spec_helper` to `~> 3.0`.  However, but other dependent gems don't pin `puppetlabs_spec_helper`, leading to test failures with the error: 

```
LoadError: cannot load such file -- puppetlabs_spec_helper/tasks/beaker
```

Example failures:
* https://gitlab.com/simp/rubygem-simp-rspec-puppet-facts/-/jobs/2103041140

**Comment by op-ct** [comment]
FYI `simp-rake-helpers.gemspec` from [rubygem-simp-rake-helpers](https://github.com/simp/rubygem-simp-rake-helpers) nails `puppetlabs_spec_helper` to `~> 2.0`

```
s.add_runtime_dependency 'puppetlabs_spec_helper',  '~> 2.0'
```

https://github.com/simp/rubygem-simp-rake-helpers/blob/master/simp-rake-helpers.gemspec#L31

**Comment by trevor-vaughan** [comment]
We'll probably need to backport whatever they ripped out into our libraries. Or see if Vox did something with it.

**Comment by ekohl** [comment]
I was the one who suggested to remove it from puppetlabs_spec_helper in favor of using beaker-rspec:
https://github.com/voxpupuli/beaker-rspec/blob/master/lib/beaker-rspec/rake_task.rb declares it. If there are features missing, they should be added there IMHO.
