### ISSUE TITLE
Broken GTX 770 - nvidia modular diagnostic software

### ISSUE THREAD

**Issue by TMKaczor** [simp/rubygem-simp-beaker-helpers#169]
Hey. My graphics card stopped working, so i found on youtube a programme called "nvidia modular diagnostic software". After running it, instead of working, there is a text "hid-generic *numbers*: device has no listeners, quitting". After that there is some stuff, but its not what it should be. Could someone help me?

**Comment by trevor-vaughan** [comment]
@TMKaczor I think you've hit the wrong repo with this question unfortunately. Best of luck with your issue though.

**Comment by TMKaczor** [comment]
> @TMKaczor I think you've hit the wrong repo with this question unfortunately. Best of luck with your issue though.

where should i post this question? This is so complicated :(

**Comment by trevor-vaughan** [comment]
@TMKaczor Sorry, I'm not sure. This is part of a project for automatically security operating systems.
