### ISSUE TITLE
GitHub release broken with unspecified error 

### ISSUE THREAD

**Issue by op-ct** [simp/rubygem-simp-beaker-helpers#182]
https://github.com/simp/rubygem-simp-beaker-helpers/runs/6234499114?check_suite_focus=true

**Comment by trevor-vaughan** [comment]
I'm guessing that this may have been caused due to a tag being pushed that wasn't connected to any known branch.

Like the one for [1.25.0](https://github.com/simp/rubygem-simp-beaker-helpers/commit/2617ab7cfa74aab546d604195c881a1de59b516f)

**Comment by op-ct** [comment]
Fixed by #183
