### ISSUE TITLE
sed -c (--copy) doesn't exist on Debian (10)

### ISSUE THREAD

**Issue by ekohl** [simp/rubygem-simp-beaker-helpers#185]
This comes from here:
https://github.com/simp/rubygem-simp-beaker-helpers/blob/fa5b6b9839fb079920e2d10c3faf0ef6826aa4cb/lib/simp/beaker_helpers.rb#L691

On Debian 10 it shows:

```
debian10-64-1 13:41:36$ sed -ci 's/debian10-64-1.*/debian10-64-1.beaker.test debian10-64-1/' /etc/hosts
  sed: invalid option -- 'c'
  Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...
```

I do wonder if it should attempt to use `hostnamectl` if available. That should solve all issues.

However, then it's also used in `enable_fips_mode_on`:
https://github.com/simp/rubygem-simp-beaker-helpers/blob/fa5b6b9839fb079920e2d10c3faf0ef6826aa4cb/lib/simp/beaker_helpers.rb#L486

**Comment by trevor-vaughan** [comment]
@ekohl We should definitely use `hostnamectl` if it exists on the system.

I vaguely remember switching to this form when I had issues with `sed` and copying the file back into place. We need some method of doing an in-place transform.

We might be able to get away with pure `ed` since these are very simple transforms.

**Comment by ekohl** [comment]
I also realized that it may be easier to ensure the systems already have a domain set beforehand. Today we do that in https://github.com/voxpupuli/puppet_metadata when we generate the boxes as a test matrix, but I've thought about pushing it into https://github.com/voxpupuli/beaker-hostgenerator as an option, maybe even defaulting to boxes having FQDNs. Today I can use this as a workaround already.

**Comment by trevor-vaughan** [comment]
I figured out an alternative POSIX-y way to do it.

I'll check for `hostnamectl` first and fall back to `sed -e 's/#{hostname}.*/#{new_fqdn} #{hostname}/' /etc/hosts 1<> /etc/hosts`
