### ISSUE TITLE
Fails on rhel images in GCP

### ISSUE THREAD

**Issue by jaevans** [simp/rubygem-simp-beaker-helpers#195]
Pay-as-you-go images in GCP don't use `subscription-manager` to manage repositories. Currently the code fails when `BEAKER_RHSM_USER` and `BEAKER_RHSM_PASS` aren't set, and if they are make calls to `subscription-manager`, so setting them to "junk" values still won't work on GCP.

**Comment by AndyAdrian-OP** [comment]
closing, fixed with #196
